Repository OpenMined/PyGrid, pull requests merged in 2020-08, with the labels that each got.

#684 Create Role model in Node DB
  apps/node/poetry.lock
  apps/node/pyproject.toml
  apps/node/src/app/__init__.py
  apps/node/src/app/main/__init__.py
  apps/node/src/app/main/users/__init__.py
  apps/node/src/app/main/users/role.py
  apps/node/tests/database/users/__init__.py
  apps/node/tests/database/users/presets/role.py
  apps/node/tests/database/users/test_role.py
Labels: Type: Epic :call_me_hand:

#683 Create User model in Network DB
  apps/network/src/users/__init__.py
  apps/network/src/users/user.py
  apps/network/tests/database/presets/user.py
  apps/network/tests/database/test_role.py
  apps/network/tests/database/test_user.py
Labels: Type: Epic :call_me_hand:

#686 Add support for FSS online key generation for data centric workers
  README.md
  apps/node/src/app/main/events/data_centric/syft_events.py
Labels: Type: New Feature :heavy_plus_sign:, encryption

#687 Fix dataset search
  apps/network/src/routes/network.py
  apps/node/src/__main__.py
  docker-compose.yml
Labels: Priority: 1 - Immediate :fire:, Severity: 2 - High :cold_sweat:, Type: Bug :bug:

#688 Create Group model in Node DB
  apps/node/src/app/main/users/__init__.py
  apps/node/src/app/main/users/group.py
  apps/node/tests/database/users/presets/group.py
  apps/node/tests/database/users/test_group.py
Labels: Type: Epic :call_me_hand:

#690 Improve websocket performance
  apps/node/poetry.lock
  apps/node/pyproject.toml
  apps/node/src/app/__init__.py
  apps/node/src/app/util.py
Labels: Priority: 2 - High :cold_sweat:, Severity: 3 - Medium :unamused:, Type: Improvement :chart_with_upwards_trend:

#691 Update default ports
  README.md
  apps/network/src/__main__.py
  apps/node/src/__main__.py
  docker-compose.yml
Labels: Status: Review Needed :raising_hand:, Type: Documentation :books:, Type: Improvement :chart_with_upwards_trend:

#692 Create User model in Node DB
  apps/node/src/app/main/users/__init__.py
  apps/node/src/app/main/users/user.py
  apps/node/src/app/main/users/usergroup.py
  apps/node/tests/database/users/presets/user.py
  apps/node/tests/database/users/presets/usergroup.py
  apps/node/tests/database/users/test_user.py
  apps/node/tests/database/users/test_usergroup.py
Labels: Type: Epic :call_me_hand:

#694 Add data-centric mnist tutorial
  .pre-commit-config.yaml
  README.md
  apps/node/poetry.lock
  apps/node/pyproject.toml
  docker-compose.yml
  examples/README.md
  examples/data-centric/mnist/01-FL-mnist-populate-a-grid-node.ipynb
  examples/data-centric/mnist/02-FL-mnist-train-model.ipynb
  tests/__init__.py
  tests/conftest.py
  tests/notebooks/__init__.py
  tests/notebooks/test_notebooks.py
Labels: Priority: 3 - Medium :unamused:, PyGrid, Status: Completed :heavy_check_mark:, Status: Review Needed :raising_hand:, federated learning, tutorials

#678 Initial AWS Serverfull Deployment using Terraform
  .gitignore
  deploy/Readme.md
  deploy/deploy.sh
  deploy/main.tf
  deploy/variables.tf
Labels: PyGrid, Status: In Progress :star2:, Status: Investigating :mag:, Status: Review Needed :raising_hand:, Type: Epic :call_me_hand:, Type: New Feature :heavy_plus_sign:, federated learning
