Repository OpenMined/PyGrid, pull requests merged in 2020-02, with the labels that each got.

#458 Create Federated Learning Processes
  gateway/app/main/processes/__init__.py
  gateway/app/main/processes/controller.py
  gateway/app/main/processes/federated_learning_process.py
Labels: federated learning

#480 Protocol download endpoint
  gateway/app/main/routes.py
Labels: PyGrid, federated learning

#484 Setup GH Actions Workflow for Automated Docker build
  .github/workflows/docker-build.yml
  .github/workflows/run-tests.yml
Labels: enhancement

#479 pr for feedback fl_impFLcycles - use server config
  gateway/app/main/routes.py
Labels: PyGrid, federated learning
