Repository OpenMined/PyGrid, pull requests merged in 2020-03, with the labels that each got.

#481 PyGrid Gateway Persistence
  gateway/app/main/__init__.py
  gateway/app/main/auth/controller.py
  gateway/app/main/codes.py
  gateway/app/main/events/__init__.py
  gateway/app/main/events/fl_events.py
  gateway/app/main/exceptions.py
  gateway/app/main/persistence/models.py
  gateway/app/main/processes/controller.py
  gateway/app/main/routes.py
  gateway/app/main/storage/__init__.py
  gateway/app/main/storage/manager.py
  gateway/app/main/storage/models.py
  gateway/app/main/storage/warehouse.py
  gateway/requirements.txt
  test/test_database.py
  test/test_gateway_sockets.py
Labels: PyGrid, federated learning

#505 Remove scope
  gateway/app/main/auth/worker.py
  gateway/app/main/events/__init__.py
  gateway/app/main/events/webrtc_events.py
  gateway/app/main/scopes/__init__.py
  gateway/app/main/scopes/controller.py
  gateway/app/main/scopes/scope.py
Labels: code quality

#482 Add federated/get-plan route
  gateway/app/main/routes.py
Labels: PyGrid, federated learning

#511 Remove scope tests
  test/test_gateway_sockets.py
Labels: code quality

#523 Create gunicorn dev conf
  gateway/dev_server.conf.py
  gateway/dev_server.sh
Labels: enhancement

#525 Create docs with running instructions for grid gateway and node
  README.md
  app/websocket/README.md
  gateway/README.md
Labels: documentation
