Repository OpenMined/PyGrid, pull requests merged in 2020-10, with the labels that each got.

#736 Add init files
  apps/network/src/app/users/__init__.py
  apps/node/src/app/main/events/data_centric/__init__.py
  apps/node/src/app/main/events/model_centric/__init__.py
  apps/node/src/app/main/routes/data_centric/__init__.py
  apps/node/src/app/main/routes/model_centric/__init__.py
Labels: Priority: 4 - Low :sunglasses:, Severity: 4 - Low :sunglasses:, Status: Completed :heavy_check_mark:

#729 Add model-centric tutorial
  examples/model-centric/01-Create-plan.ipynb
  examples/model-centric/02-ExecutePlan.ipynb
  tests/__init__.py
  tests/notebooks/test_notebooks.py
Labels: PyGrid, Status: Completed :heavy_check_mark:, federated learning, tutorials

#741 Add Network Database (Pygrid 0.3.0)
  apps/network/poetry.lock
  apps/network/pyproject.toml
  apps/network/src/__main__.py
  apps/network/src/app.py
  apps/network/src/main/codes.py
  apps/network/src/main/core/database/__init__.py
  apps/network/src/main/core/database/groups/__init__.py
  apps/network/src/main/core/database/groups/groups.py
  apps/network/src/main/core/database/groups/usergroup.py
  apps/network/src/main/core/database/roles/roles.py
  apps/network/src/main/core/database/users/__init__.py
  apps/network/src/main/core/database/users/user.py
  apps/network/src/main/core/database/utils.py
  apps/network/src/main/exceptions.py
  apps/network/src/main/routes/auth.py
  apps/network/src/main/routes/roles/role_ops.py
  apps/network/src/main/routes/roles/routes.py
  apps/network/tests/conftest.py
  apps/network/tests/test_routes/test_roles.py
Labels: Type: New Feature :heavy_plus_sign:

#744 Remove mocking from role endpoints (domain)
  apps/domain/poetry.lock
  apps/domain/pyproject.toml
  apps/domain/src/__main__.py
  apps/domain/src/app.py
  apps/domain/src/main/codes.py
  apps/domain/src/main/core/database/__init__.py
  apps/domain/src/main/core/database/utils.py
  apps/domain/src/main/exceptions.py
  apps/domain/src/main/routes/auth.py
  apps/domain/src/main/routes/roles/role_ops.py
  apps/domain/src/main/routes/roles/routes.py
  apps/domain/tests/conftest.py
  apps/domain/tests/test_routes/test_roles.py
  apps/domain/tests/test_routes/test_roles_http.py
Labels: Type: Improvement :chart_with_upwards_trend:, Type: New Feature :heavy_plus_sign:

#745 Add logic for user endpoints in domain (0.3.0)
  apps/domain/poetry.lock
  apps/domain/pyproject.toml
  apps/domain/src/app.py
  apps/domain/src/main/core/database/__init__.py
  apps/domain/src/main/routes/users/routes.py
  apps/domain/src/main/routes/users/user_ops.py
  apps/domain/tests/test_routes/test_users.py
  apps/domain/tests/test_routes/test_users_http.py
Labels: Type: Improvement :chart_with_upwards_trend:, Type: New Feature :heavy_plus_sign:

#743 Extend CLI to support serverless deployment via the Infrastructure-API
  .gitignore
  apps/cli/providers/__init__.py
  apps/cli/providers/aws.py
  apps/cli/providers/provider.py
  apps/cli/tf.py
  apps/infrastructure/api/__init__.py
  apps/infrastructure/api/__main__.py
  apps/infrastructure/api/providers/__init__.py
  apps/infrastructure/api/providers/aws/__init__.py
  apps/infrastructure/api/providers/aws/aws.py
  apps/infrastructure/api/providers/aws/serverfull.py
  apps/infrastructure/api/providers/aws/serverless.py
  apps/infrastructure/api/providers/aws/utils.py
  apps/infrastructure/api/providers/azure/__init__.py
  apps/infrastructure/api/providers/azure/azure.py
  apps/infrastructure/api/providers/gcp/__init__.py
  apps/infrastructure/api/providers/gcp/gcp.py
  apps/infrastructure/api/providers/provider.py
  apps/infrastructure/api/providers/utils.py
  apps/infrastructure/api/tf.py
  apps/infrastructure/cli/__init__.py
  apps/infrastructure/cli/cli.py
  apps/infrastructure/cli/deploy.py
  apps/infrastructure/cli/provider_utils/aws.py
  apps/infrastructure/cli/provider_utils/azure.py
  apps/infrastructure/cli/provider_utils/gcp.py
  apps/infrastructure/cli/utils.py
  apps/node/src/app/templates/index.html
  deploy/serverless-network/database.tf
  deploy/serverless-network/lambda.tf
  setup.py
Labels: Deployment, Status: In Progress :star2:, Type: Epic :call_me_hand:, Type: Refactor :hammer:
