Repository OpenMined/PyGrid, pull requests merged in 2020-07, with the labels that each got.

#594 Hook up Static FL Auth to websocket endpoints
  grid/app/main/auth/__init__.py
  grid/app/main/auth/federated.py
  grid/app/main/events/fl_events.py
  grid/app/main/routes/federated.py
  test/test_gateway_sockets.py
Labels: Type: Improvement :chart_with_upwards_trend:

#601 Fix authentication flow - #594
  grid/app/__init__.py
  grid/app/main/auth/federated.py
  grid/app/main/events/fl_events.py
  grid/app/main/routes/federated.py
  grid/app/main/tasks/cycle.py
  pip-dep/requirements.txt
  test/test_gateway_sockets.py
Labels: Type: Refactor :hammer:

#603 add min_diffs/max_diffs for averaging readiness
  grid/app/main/cycles/cycle_manager.py
Labels: Type: Improvement :chart_with_upwards_trend:

#605 Replace hardcoded avg plan with uploaded avg plan
  grid/app/main/sfl/cycles/cycle_manager.py
  grid/grid.pyc
Labels: Type: Improvement :chart_with_upwards_trend:

#607 fix pygrid entrypoints for dev script and docker
  dev_server.conf.py
  dev_server.sh
  docker-compose.yml
  entrypoint.sh
  grid/__main__.py
Labels: Type: Bug :bug:

#609 create public get-model route
  grid/app/main/routes/sfl/routes.py
Labels: Type: New Feature :heavy_plus_sign:

#610 update references/imports from syft
  grid/app/main/codes.py
  grid/app/main/dfl/auth/session_repository.py
  grid/app/main/dfl/auth/user_session.py
  grid/app/main/dfl/persistence/object_storage.py
  grid/app/main/events/dfl/control_events.py
  grid/app/main/routes/dfl/routes.py
  pip-dep/requirements.txt
  test/conftest.py
Labels: Type: Bug :bug:, Type: Refactor :hammer:

#612 Take GRID_PORT into account in entrypoint.sh
  entrypoint.sh
Labels: Status: Review Needed :raising_hand:, Type: Bug :bug:

#613 update conditions to accept cycle requests
  grid/app/main/sfl/controller/fl_controller.py
  grid/app/main/sfl/cycles/cycle_manager.py
  grid/app/main/sfl/syft_assets/plan_manager.py
Labels: Type: Improvement :chart_with_upwards_trend:

#616 Bump syft version to 0.2.7
  pip-dep/requirements.txt
Labels: dependencies

#618 fix auth http endpoint
  grid/app/main/routes/sfl/routes.py
Labels: Type: Bug :bug:

#623 Fix static FL "get-model" route
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/controller/fl_controller.py
  grid/app/main/sfl/workers/worker_manager.py
Labels: Status: Review Needed :raising_hand:, Type: Bug :bug:

#625 Checkpoints retrieval by number and alias
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/models/ai_model.py
  grid/app/main/sfl/models/model_manager.py
  grid/app/main/storage/warehouse.py
Labels: Status: Review Needed :raising_hand:, Type: Bug :bug:, Type: Improvement :chart_with_upwards_trend:

#614 Auto formatting
  .github/workflows/run-tests.yml
  .pre-commit-config.yaml
  Makefile
  dev_server.conf.py
  grid/__main__.py
  grid/app/__init__.py
  grid/app/main/__init__.py
  grid/app/main/core/__init__.py
  grid/app/main/core/codes.py
  grid/app/main/core/exceptions.py
  grid/app/main/dfl/auth/__init__.py
  grid/app/main/dfl/auth/session_repository.py
  grid/app/main/dfl/auth/user_session.py
  grid/app/main/dfl/persistence/database.py
  grid/app/main/dfl/persistence/model_cache.py
  grid/app/main/dfl/persistence/model_controller.py
  grid/app/main/dfl/persistence/model_storage.py
  grid/app/main/dfl/persistence/object_storage.py
  grid/app/main/events/__init__.py
  grid/app/main/events/dfl/control_events.py
  grid/app/main/events/dfl/model_events.py
  grid/app/main/events/dfl/syft_events.py
  grid/app/main/events/sfl/control_events.py
  grid/app/main/events/sfl/fl_events.py
  grid/app/main/events/socket_handler.py
  grid/app/main/routes/__init__.py
  grid/app/main/routes/dfl/routes.py
  grid/app/main/routes/general.py
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/auth/federated.py
  grid/app/main/sfl/controller/fl_controller.py
  grid/app/main/sfl/cycles/cycle.py
  grid/app/main/sfl/cycles/cycle_manager.py
  grid/app/main/sfl/cycles/worker_cycle.py
  grid/app/main/sfl/models/ai_model.py
  grid/app/main/sfl/models/model_manager.py
  grid/app/main/sfl/processes/config.py
  grid/app/main/sfl/processes/fl_process.py
  grid/app/main/sfl/processes/process_manager.py
  grid/app/main/sfl/syft_assets/plan.py
  grid/app/main/sfl/syft_assets/plan_manager.py
  grid/app/main/sfl/syft_assets/protocol.py
  grid/app/main/sfl/syft_assets/protocol_manager.py
  grid/app/main/sfl/tasks/cycle.py
  grid/app/main/sfl/workers/worker.py
  grid/app/main/sfl/workers/worker_manager.py
  grid/app/main/storage/warehouse.py
  grid/grid.py
  pip-dep/requirements.txt
  pip-dep/requirements_dev.txt
  setup.py
  test/conftest.py
  test/routes/test_federated.py
  test/test_database.py
  test/test_dynamic_api_sockets.py
  test/test_gateway_sockets.py
Labels: Type: Documentation :books:, Type: Improvement :chart_with_upwards_trend:, code quality

#664 Abstract fl manager
  .github/workflows/run-tests.yml
  .pre-commit-config.yaml
  Makefile
  dev_server.conf.py
  grid/__main__.py
  grid/app/__init__.py
  grid/app/main/__init__.py
  grid/app/main/core/__init__.py
  grid/app/main/core/codes.py
  grid/app/main/core/exceptions.py
  grid/app/main/core/fl_manager.py
  grid/app/main/dfl/auth/__init__.py
  grid/app/main/dfl/auth/session_repository.py
  grid/app/main/dfl/auth/user_session.py
  grid/app/main/dfl/persistence/database.py
  grid/app/main/dfl/persistence/model_cache.py
  grid/app/main/dfl/persistence/model_controller.py
  grid/app/main/dfl/persistence/model_storage.py
  grid/app/main/dfl/persistence/object_storage.py
  grid/app/main/events/__init__.py
  grid/app/main/events/dfl/control_events.py
  grid/app/main/events/dfl/model_events.py
  grid/app/main/events/dfl/syft_events.py
  grid/app/main/events/sfl/control_events.py
  grid/app/main/events/sfl/fl_events.py
  grid/app/main/events/socket_handler.py
  grid/app/main/routes/__init__.py
  grid/app/main/routes/dfl/routes.py
  grid/app/main/routes/general.py
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/auth/federated.py
  grid/app/main/sfl/controller/fl_controller.py
  grid/app/main/sfl/cycles/cycle.py
  grid/app/main/sfl/cycles/cycle_manager.py
  grid/app/main/sfl/cycles/worker_cycle.py
  grid/app/main/sfl/models/ai_model.py
  grid/app/main/sfl/models/model_manager.py
  grid/app/main/sfl/processes/config.py
  grid/app/main/sfl/processes/fl_process.py
  grid/app/main/sfl/processes/process_manager.py
  grid/app/main/sfl/syft_assets/plan.py
  grid/app/main/sfl/syft_assets/plan_manager.py
  grid/app/main/sfl/syft_assets/protocol.py
  grid/app/main/sfl/syft_assets/protocol_manager.py
  grid/app/main/sfl/tasks/cycle.py
  grid/app/main/sfl/workers/worker.py
  grid/app/main/sfl/workers/worker_manager.py
  grid/app/main/storage/warehouse.py
  grid/grid.py
  pip-dep/requirements.txt
  pip-dep/requirements_dev.txt
  setup.py
  test/conftest.py
  test/routes/test_federated.py
  test/test_database.py
  test/test_dynamic_api_sockets.py
  test/test_gateway_sockets.py
Labels: Type: Discussion :speaker:, Type: Refactor :hammer:, code quality, federated learning, work-in-progress

#622 Namespace Static & dynamic FL API routes
  grid/app/__init__.py
  grid/app/main/__init__.py
  grid/app/main/core/codes.py
  grid/app/main/events/__init__.py
  grid/app/main/events/sfl/fl_events.py
  grid/app/main/routes/dfl/routes.py
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/auth/federated.py
  grid/app/templates/index.html
  test/conftest.py
  test/routes/test_federated.py
  test/test_dynamic_api_sockets.py
  test/test_gateway_sockets.py
Labels: Type: Refactor :hammer:, federated learning

#626 Tidy up static FL DB
  grid/app/main/__init__.py
  grid/app/main/sfl/cycles/cycle.py
  grid/app/main/sfl/cycles/cycle_manager.py
  grid/app/main/sfl/cycles/worker_cycle.py
  grid/app/main/sfl/models/ai_model.py
  grid/app/main/sfl/models/model_manager.py
  grid/app/main/sfl/processes/config.py
  grid/app/main/sfl/processes/fl_process.py
  grid/app/main/sfl/syft_assets/plan.py
  grid/app/main/sfl/syft_assets/protocol.py
  grid/app/main/sfl/workers/worker.py
  pip-dep/requirements.txt
  test/test_database.py
Labels: Priority: 3 - Medium :unamused:, Severity: 3 - Medium :unamused:, Type: Improvement :chart_with_upwards_trend:

#606 Make connection speed test optional
  grid/app/main/core/codes.py
  grid/app/main/events/sfl/fl_events.py
  grid/app/main/routes/sfl/routes.py
  test/test_static_api_sockets.py
Labels: Type: Improvement :chart_with_upwards_trend:

#667 Fix invalid ModelCheckpoint DB field access
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/cycles/cycle_manager.py
Labels: Type: Bug :bug:

#668 Make speed fields in cycle-request optional; rename get-model route
  grid/app/main/events/sfl/fl_events.py
  grid/app/main/routes/sfl/routes.py
  grid/app/main/sfl/workers/worker_manager.py
  test/test_static_api_sockets.py
Labels: Type: Bug :bug:, Type: Improvement :chart_with_upwards_trend:

#673 Replace underscore_case for hyphen-case on routes
  apps/node/src/app/__init__.py
  apps/node/src/app/main/__init__.py
  apps/node/src/app/main/core/codes.py
  apps/node/src/app/main/routes/dfl/routes.py
  apps/node/src/app/main/routes/sfl/routes.py
  apps/node/tests/rest_api/model_centric/test_cycle_request.py
  apps/node/tests/rest_api/model_centric/test_report_diff.py
  tests/model_centric/test_fl_process.py
Labels: Priority: 3 - Medium :unamused:, Severity: 2 - High :cold_sweat:, Type: Improvement :chart_with_upwards_trend:

#680 Fix CI unit tests
  apps/node/setup.py
Labels: Type: Bug :bug:

#677 Create Role model in Network DB
  apps/network/poetry.lock
  apps/network/pyproject.toml
  apps/network/src/__init__.py
  apps/network/src/users/__init__.py
  apps/network/src/users/role.py
  apps/network/tests/conftest.py
  apps/network/tests/database/__init__.py
  apps/network/tests/database/presets/role.py
  apps/network/tests/database/test_role.py
Labels: Type: Epic :call_me_hand:
