Repository OpenMined/PyGrid, pull requests merged in 2020-09, with the labels that each got.

#705 Update README.md
  examples/README.md
Labels: Type: Documentation :books:

#706 Latest changes for introduction tutorial
  examples/data-centric/introduction/01-introduction-to-pygrid.ipynb
  examples/data-centric/introduction/images/1.png
  examples/data-centric/introduction/images/2.png
  examples/data-centric/introduction/images/3.png
  examples/data-centric/introduction/images/4.png
  examples/data-centric/introduction/images/5.png
  examples/data-centric/introduction/images/6.png
  examples/data-centric/introduction/images/7.png
  tests/__init__.py
  tests/conftest.py
  tests/data_centric/test_basic_syft_operations.py
  tests/notebooks/test_notebooks.py
Labels: Type: Documentation :books:

#710 Rearrange network path structure
  apps/network/run.sh
  apps/network/src/__init__.py
  apps/network/src/__main__.py
  apps/network/src/app/__init__.py
  apps/network/src/app/codes.py
  apps/network/src/app/events/__init__.py
  apps/network/src/app/events/network.py
  apps/network/src/app/events/socket_handler.py
  apps/network/src/app/network/__init__.py
  apps/network/src/app/network/network_manager.py
  apps/network/src/app/network/nodes.py
  apps/network/src/app/routes/__init__.py
  apps/network/src/app/routes/dataset.py
  apps/network/src/app/routes/general.py
  apps/network/src/app/routes/models.py
  apps/network/src/app/routes/network.py
  apps/network/src/app/routes/nodes.py
  apps/network/src/app/users/__init__.py
  apps/network/src/app/users/role.py
  apps/network/src/app/users/user.py
  apps/network/src/app/utils/__init__.py
  apps/network/src/app/utils/wrappers.py
  apps/network/src/app/workers/__init__.py
  apps/network/src/app/workers/worker.py
  apps/network/tests/conftest.py
  apps/network/tests/database/test_role.py
  apps/network/tests/database/test_user.py
  apps/network/tests/rest_api/test_choose_model_hosts.py
  apps/network/tests/rest_api/test_delete_nodes.py
  apps/network/tests/rest_api/test_join.py
  apps/network/tests/rest_api/test_search_dataset.py
  apps/network/tests/rest_api/test_search_encrypted_model.py
  apps/network/tests/rest_api/test_search_model.py
  tests/conftest.py
Labels: Priority: 2 - High :cold_sweat:, Severity: 4 - Low :sunglasses:, Type: Refactor :hammer:, code quality

#714 Add flask-lambda-python36 as dev dep in node
  apps/node/poetry.lock
  apps/node/pyproject.toml
Labels: PyGrid, Severity: 2 - High :cold_sweat:, Status: Completed :heavy_check_mark:, Type: Bug :bug:, dependencies

#715 add request id for identification
  apps/node/src/app/main/core/codes.py
  apps/node/src/app/main/events/model_centric/fl_events.py
  apps/node/src/app/main/model_centric/controller/fl_controller.py
  tests/model_centric/test_fl_process.py
Labels: Priority: 2 - High :cold_sweat:, Severity: 2 - High :cold_sweat:, Status: In Progress :star2:, federated learning

#720 Bump syft 0.2.9
  apps/node/poetry.lock
  apps/node/pyproject.toml
  docker-compose.yml
Labels: Priority: 3 - Medium :unamused:, PyGrid, Status: Completed :heavy_check_mark:, dependencies

#718 Change "can_triage_jobs" to "can_triage_requests"
  apps/node/src/app/__init__.py
  apps/node/src/app/main/database/role.py
  apps/node/src/app/main/events/role_related.py
  apps/node/src/app/main/routes/role_related.py
  apps/node/src/app/main/users/role_ops.py
  apps/node/src/app/main/users/user_ops.py
  apps/node/tests/database/users/test_role.py
  apps/node/tests/rest_api/users/test_roles_http.py
  apps/node/tests/websocket_api/test_roles_ws.py
Labels: Type: Improvement :chart_with_upwards_trend:

#719 Add "can_upload_data" to Role in Node
  apps/node/src/app/__init__.py
  apps/node/src/app/main/database/role.py
  apps/node/src/app/main/routes/role_related.py
  apps/node/src/app/main/users/role_ops.py
  apps/node/tests/database/users/presets/role.py
  apps/node/tests/database/users/test_role.py
  apps/node/tests/rest_api/users/test_roles_http.py
  apps/node/tests/rest_api/users/test_users_http.py
  apps/node/tests/websocket_api/test_roles_ws.py
  apps/node/tests/websocket_api/test_users_ws.py
Labels: Type: Improvement :chart_with_upwards_trend:

#724 Change "can_manage_roles" to "can_manage_nodes" in Network
  apps/network/src/app/__init__.py
  apps/network/src/app/users/role.py
  apps/network/tests/database/test_role.py
Labels: Type: Bug :bug:

#727 Create Node API endpoints for Groups
  apps/node/src/app/main/core/codes.py
  apps/node/src/app/main/events/__init__.py
  apps/node/src/app/main/events/group_related.py
  apps/node/src/app/main/routes/__init__.py
  apps/node/src/app/main/routes/group_related.py
  apps/node/src/app/main/users/group_ops.py
  apps/node/src/app/main/users/role_ops.py
  apps/node/tests/rest_api/users/test_groups_http.py
  apps/node/tests/websocket_api/test_groups_ws.py
Labels: Type: Epic :call_me_hand:

#728 Create Network API endpoints for Users
  apps/network/poetry.lock
  apps/network/pyproject.toml
  apps/network/src/app/__init__.py
  apps/network/src/app/auth.py
  apps/network/src/app/codes.py
  apps/network/src/app/database/__init__.py
  apps/network/src/app/database/role.py
  apps/network/src/app/database/user.py
  apps/network/src/app/database/utils.py
  apps/network/src/app/events/__init__.py
  apps/network/src/app/events/user_related.py
  apps/network/src/app/exceptions.py
  apps/network/src/app/routes/__init__.py
  apps/network/src/app/routes/user_related.py
  apps/network/src/app/users/__init__.py
  apps/network/src/app/users/user_ops.py
  apps/network/tests/database/test_role.py
  apps/network/tests/database/test_user.py
  apps/network/tests/rest_api/test_users_http.py
  apps/network/tests/websocket_api/test_users_ws.py
Labels: Type: Epic :call_me_hand:

#731 Create Network API endpoints for Roles
  apps/network/src/app/codes.py
  apps/network/src/app/events/__init__.py
  apps/network/src/app/events/role_related.py
  apps/network/src/app/routes/__init__.py
  apps/network/src/app/routes/role_related.py
  apps/network/src/app/users/role_ops.py
  apps/network/tests/rest_api/test_roles_http.py
  apps/network/tests/websocket_api/test_roles_ws.py
Labels: Type: Epic :call_me_hand:

#730 Handle request_id globally
  apps/node/src/app/main/events/__init__.py
  apps/node/src/app/main/events/data_centric/control_events.py
  apps/node/src/app/main/events/data_centric/model_events.py
  apps/node/src/app/main/events/model_centric/control_events.py
  apps/node/src/app/main/events/model_centric/fl_events.py
  apps/node/src/app/main/events/role_related.py
  apps/node/src/app/main/events/user_related.py
  apps/node/tests/websocket_api/test_roles_ws.py
  apps/node/tests/websocket_api/test_users_ws.py
Labels: Type: Bug :bug:, Type: Improvement :chart_with_upwards_trend:

#701 Serverless deployment of Node on AWS (HTTP)
  .gitignore
  apps/node/poetry.lock
  apps/node/pyproject.toml
  apps/node/src/app/__init__.py
  apps/node/src/deploy.py
  deploy/serverfull-node/main.tf
  deploy/serverless-node/api_gateway.tf
  deploy/serverless-node/database.tf
  deploy/serverless-node/deploy.sh
  deploy/serverless-node/ec2.tf
  deploy/serverless-node/efs.tf
  deploy/serverless-node/iam.tf
  deploy/serverless-node/lambda-layer/create_zip_file.sh
  deploy/serverless-node/lambda-layer/readme.md
  deploy/serverless-node/lambda-layer/requirements.txt
  deploy/serverless-node/lambda.tf
  deploy/serverless-node/lambda_layer.tf
  deploy/serverless-node/networking.tf
  deploy/serverless-node/outputs.tf
  deploy/serverless-node/readme.md
  deploy/serverless-node/secret_manager.tf
  deploy/serverless-node/variables.tf
  deploy/serverless-node/vpc.tf
Labels: Status: In Progress :star2:, Type: Epic :call_me_hand:, dependencies

#709 PyGrid CLI
  README.md
  apps/cli/__init__.py
  apps/cli/cli.py
  apps/cli/deploy.py
  apps/cli/providers/__init__.py
  apps/cli/providers/aws.py
  apps/cli/providers/azure.py
  apps/cli/providers/gcp.py
  apps/cli/providers/provider.py
  apps/cli/tf.py
  apps/cli/utils.py
  setup.py
Labels: Type: Epic :call_me_hand:
