Repository OpenMined/PyGrid, pull requests merged in 2020-06, with the labels that each got.

#582 Remove grid nodes network endpoints
  grid/app/main/network/__init__.py
  grid/app/main/network/network_manager.py
  grid/app/main/network/nodes.py
  grid/app/main/routes/__init__.py
  grid/app/main/routes/network.py
  test/routes/test_network.py
Labels: Priority: 2 - High :cold_sweat:, Type: Refactor :hammer:

#584 Add support section
  README.md
Labels: Priority: 3 - Medium :unamused:, Severity: 4 - Low :sunglasses:

#592 Accept cycle requests when server_config.num_cycles = 0
  grid/app/main/controller/fl_controller.py
Labels: Type: New Feature :heavy_plus_sign:
