Repository OpenMined/PyGrid, pull requests merged in 2021-04, with the labels that each got.

#838 Fix/Tenseal version
  apps/domain/poetry.lock
  apps/domain/pyproject.toml
  apps/network/poetry.lock
  apps/network/pyproject.toml
  apps/worker/poetry.lock
  apps/worker/pyproject.toml
Labels: dependencies

#837 Update readme example
  examples/README.md
  examples/experimental/data-centric/basic_access_management/Automatic Data Access Management - Data Owner.ipynb
  examples/experimental/data-centric/basic_access_management/Automatic Data Access Management - Data Scientist.ipynb
  examples/experimental/data-centric/mnist/MNIST Training - Data Owner.ipynb
  examples/experimental/data-centric/mnist/MNIST Training - Data Scientist.ipynb
Labels: Type: Documentation :books:

#834 Update pre-commit to include checks of documentation
  .github/workflows/tests.yml
  .pre-commit-config.yaml
Labels: PyGrid, code quality

#829 Fix/813
  .github/workflows/tests.yml
  apps/domain/src/app.py
  apps/domain/src/main/core/database/setup/setup.py
  apps/domain/src/main/core/exceptions.py
  apps/domain/src/main/core/node.py
  apps/domain/src/main/core/services/setup_service.py
  apps/domain/src/main/core/sleepy_until_configured.py
  apps/domain/src/main/routes/auth.py
  apps/domain/src/main/routes/setup/routes.py
  apps/domain/tests/test_routes/test_setup.py
Labels: Status: In Progress :star2:

#839 Datasets refactory
  apps/domain/src/main/core/database/bin_storage/bin_obj.py
  apps/domain/src/main/core/database/dataset/datasetgroup.py
  apps/domain/src/main/core/datasets/dataset_ops.py
  apps/domain/src/main/core/exceptions.py
  apps/domain/src/main/core/services/association_request.py
  apps/domain/src/main/core/services/dataset_service.py
  apps/domain/src/main/routes/data_centric/datasets/routes.py
  apps/domain/tests/test_routes/test_dataset.py
Labels: Priority: 1 - Immediate :fire:, Severity: 4 - Low :sunglasses:, Type: New Feature :heavy_plus_sign:, Type: Refactor :hammer:
