Repository OpenMined/PyGrid, pull requests merged in 2021-05, with the labels that each got.

#857 Make success code customizable for APIs
  apps/domain/src/main/routes/association_requests/routes.py
  apps/domain/src/main/routes/auth.py
  apps/domain/src/main/routes/data_centric/datasets/routes.py
  apps/domain/src/main/routes/data_centric/requests/routes.py
  apps/domain/src/main/routes/data_centric/tensors/routes.py
  apps/domain/src/main/routes/data_centric/workers/routes.py
  apps/domain/src/main/routes/general/routes.py
  apps/domain/src/main/routes/groups/routes.py
  apps/domain/src/main/routes/roles/routes.py
  apps/domain/src/main/routes/search/routes.py
  apps/domain/src/main/routes/setup/routes.py
  apps/domain/src/main/routes/users/routes.py
  apps/domain/tests/test_routes/test_requests.py
  apps/domain/tests/test_routes/test_roles_http.py
  apps/domain/tests/test_routes/test_tensors.py
  apps/domain/tests/test_routes/test_users_http.py
Labels: Type: Improvement :chart_with_upwards_trend:

#862 Add unit tests to grid's disk_store
  apps/domain/src/main/core/database/store_disk.py
  apps/domain/tests/test_database/test_disk_store.py
Labels: Type: Testing :test_tube:

#859 Fix 858
  apps/domain/src/app.py
  apps/domain/src/main/core/exceptions.py
  apps/domain/src/main/core/services/setup_service.py
  apps/domain/src/main/routes/auth.py
  apps/domain/src/main/routes/setup/routes.py
  apps/domain/tests/test_routes/test_setup.py
Labels: Type: Refactor :hammer:
